In [1]:
import pandas as pd

df = pd.read_excel(r"C:\AI Project\AI_Resume_Screening.csv.xlsx")
print(df.shape)
print(df.columns.tolist())
df.head()

(1000, 11)
['Resume_ID', 'Name', 'Skills', 'Experience (Years)', 'Education', 'Certifications', 'Job Role', 'Recruiter Decision', 'Salary Expectation ($)', 'Projects Count', 'AI Score (0-100)']

,Resume_ID,Name,Skills,Experience (Years),Education,Certifications,Job Role,Recruiter Decision,Salary Expectation ($),Projects Count,AI Score (0-100)
0,1,Ashley Ali,"TensorFlow, NLP, Pytorch",10,B.Sc,NaN,AI Researcher,Hire,104895,8,100
1,2,Wesley Roman,"Deep Learning, Machine Learning, Python, SQL",10,MBA,Google ML,Data Scientist,Hire,113002,1,100
2,3,Corey Sanchez,"Ethical Hacking, Cybersecurity, Linux",1,MBA,Deep Learning Specialization,Cybersecurity Analyst,Hire,71766,7,70
3,4,Elizabeth Carney,"Python, Pytorch, TensorFlow",7,B.Tech,AWS Certified,AI Researcher,Hire,46848,0,95
4,5,Julie Hill,"SQL, React, Java",4,PhD,NaN,Software Engineer,Hire,87441,9,100

In [2]:
# Step 1: Import all libraries
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, classification_report
import warnings
warnings.filterwarnings('ignore')

# Step 2: Load dataset
df = pd.read_excel(r"C:\AI Project\AI_Resume_Screening.csv.xlsx")
print("Dataset loaded successfully!")
print(f"Shape: {df.shape}")
df.head()

Dataset loaded successfully!
Shape: (1000, 11)

,Resume_ID,Name,Skills,Experience (Years),Education,Certifications,Job Role,Recruiter Decision,Salary Expectation ($),Projects Count,AI Score (0-100)
0,1,Ashley Ali,"TensorFlow, NLP, Pytorch",10,B.Sc,NaN,AI Researcher,Hire,104895,8,100
1,2,Wesley Roman,"Deep Learning, Machine Learning, Python, SQL",10,MBA,Google ML,Data Scientist,Hire,113002,1,100
2,3,Corey Sanchez,"Ethical Hacking, Cybersecurity, Linux",1,MBA,Deep Learning Specialization,Cybersecurity Analyst,Hire,71766,7,70
3,4,Elizabeth Carney,"Python, Pytorch, TensorFlow",7,B.Tech,AWS Certified,AI Researcher,Hire,46848,0,95
4,5,Julie Hill,"SQL, React, Java",4,PhD,NaN,Software Engineer,Hire,87441,9,100

In [5]:
# preparing data for model
le = LabelEncoder()

# converting text columns to numbers
df['Education_enc'] = le.fit_transform(df['Education'])
df['Job_Role_enc'] = le.fit_transform(df['Job Role'])

# target variable
df['Target'] = le.fit_transform(df['Recruiter Decision'])  # Hire=0, Reject=1

# features jo model use karega
features = ['Experience (Years)', 'AI Score (0-100)', 
            'Projects Count', 'Salary Expectation ($)', 
            'Education_enc', 'Job_Role_enc']

X = df[features]
y = df['Target']

print("Features ready!")
print(X.shape)

Features ready!
(1000, 6)

In [6]:
# splitting data into train and test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# training the model
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# checking accuracy
y_pred = model.predict(X_test)
acc = accuracy_score(y_test, y_pred)
print(f"Model Accuracy: {acc * 100:.2f}%")

Model Accuracy: 100.00%

In [7]:
import pickle

# saving the model
with open(r"C:\AI Project\model.pkl", "wb") as f:
    pickle.dump(model, f)

# saving label encoder bhi
with open(r"C:\AI Project\encoder.pkl", "wb") as f:
    pickle.dump(le, f)

print("Model saved successfully!")

Model saved successfully!